### ISSUE TITLE
Minor release for new Base methods

### ISSUE THREAD

**Issue by moble** [brianguenter/FastDifferentiation.jl#86]
Can we have a new release to include the new methods in Base, please?  I'm currently keeping those methods in the FastDifferentiation extension to a package of mine, which I'd like to get cleaned out and just depend on the latest version of FD.

**Comment by brianguenter** [comment]
I tried the register package workflow and got a warning about using node.js 16 instead of 20. The workflow then failed with this error message. Do you know how to fix this?

```
Run julia-actions/RegisterAction@latest
RequestError [HttpError]: Resource not accessible by integration
    at /home/runner/work/_actions/julia-actions/RegisterAction/latest/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (/home/runner/work/_actions/julia-actions/RegisterAction/latest/register.js:22:18) {
  status: '403',
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Tue, 02 Jul 2024 17:14:17 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'istio-envoy',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept-Encoding, Accept, X-Requested-With',
    'x-accepted-github-permissions': 'contents=write; contents=write,workflows=write',
    'x-content-type-options': 'nosniff',
    'x-envoy-upstream-service-time': '63',
    'x-frame-options': 'deny',
    'x-github-api-version-selected': '2022-11-28',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': 'FC81:2F4376:94F82B:1133454:66843569',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4992',
    'x-ratelimit-reset': '1719943769',
    'x-ratelimit-resource': 'core',
    'x-ratelimit-used': '8',
    'x-xss-protection': '0'
  },
  request: {
    method: 'PUT',
    url: 'https://api.github.com/repos/brianguenter/FastDifferentiation.jl/contents/Project.toml',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-core.js/3.2.1 Node.js/16.20.2 (linux; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
  
    request: { agent: [Agent], hook: [Function: bound bound register] }
  },
  documentation_url: 'https://docs.github.com/rest/repos/contents#create-or-update-file-contents'
}
```

**Comment by moble** [comment]
Ooh, that's a new one.  Looking back at [the last time I ran](https://github.com/moble/PostNewtonian.jl/actions/runs/9719274531) 4 days ago, there was just a warning.  But github [did say they intend to deprecate soon](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).  It might be worth just trying again, since they sometimes start random errors just before making a permanent change like this.  Otherwise, we might have to see if [my PR](https://github.com/julia-actions/RegisterAction/pull/18) works out.

Meanwhile, just the usual JuliaRegistrator comment should still work.

Sorry about that.

**Comment by brianguenter** [comment]
JuliaRegistrator is doing its thing. Should have a new release in 15-20 minutes.

**Comment by moble** [comment]
Awesome.  Thanks so much for this and the package generally.  We're seeing awesome performance!
